name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - run: git submodule update --init --recursive

      - name: Install dependencies
        run: yarn install

      - name: Run build
        run: CI=false yarn build